# Generated by Django 3.2.4 on 2021-07-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('Student_name', models.CharField(max_length=100)),
                ('Student_mail', models.EmailField(max_length=100)),
                ('Student_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
